title = "EllinaKuznetcova"
description = "Description"
baseurl = "https://ellinakuznetcova.gitlab.io/"
languageCode = "en-us"
theme = "dimension"

[Params]
	title = "Ellina Kuznetcova"
	description = "iOS developer"
