baseurl = "https://ellinakuznetcova.github.io"
languageCode = "en-us"
theme = "hugo-goa"
author = "Ellina Kuznetcova"
title = "Ellina Kuznetcova"

enableRobotsTXT = true
googleAnalytics = "UA-102087913-1"

## Site Settings
[params]
author = "Ellina Kuznetcova"
intro = "Software Developer"
description = "iOS development"
authorimage = "avatar.jpeg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Ellina Kuznetcova Software Development"
keywords = "iOS,Swift,Objective-C,software development,developer"

## Social Accounts
[params.social]
github = "EllinaKuznetcova"
instagram = "lilluellu"
medium = "ellinakuznetcova"
linkedin = "ellinakuznetcova"
twitter = "lilluellu"
email = "ellina09.19@gmail.com"
resume = "Ellina%20Kuznetcova%27s%20CV.pdf"

## Extras
[params.extra]
copyright = ""
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]

# Credits
#[[params.credits]]
# Title is used as URL text
#title = "HTML5UP"
# Text will be used to explain the credit
#text = "Design by"
#link = "https://html5up.net"
