title = "EllinaKuznetcova"
description = "Description"
baseurl = "https://ellinakuznetcova.gitlab.io/"
languageCode = "en-us"
theme = "hugo-identity-theme"

enableRobotsTXT = true
googleAnalytics = "UA-102087913-1"

[params]
	[params.personal]
		name = "Ellina Kuznetcova"
		position = "iOS developer"
		avatar = "avatar.png"

    [[params.social]]
	    title = "Twitter"
	    icon = "fa-twitter"
	    link = "https://twitter.com/lillu_ellu"

	[[params.social]]
	    title = "Instagram"
	    icon = "fa-instagram"
	    link = "https://www.instagram.com/lilluellu/"
	
	[[params.social]]
	    title = "Github"
	    icon = "fa-github"
	    link = "https://github.com/EllinaKuznetcova"

	[[params.social]]
		title = "LinkedIn"
		icon = "fa-linkedin"
		link = "https://www.linkedin.com/in/ellinakuznetcova"

	[[params.social]]
		title = "email"
		icon = "fa-envelope-o"
		link = "mailto:ellina09.19@gmail.com"

	[[params.social]]
		title = "cv"
		icon = "fa-info"
		link = "Ellina Kuznetcova's CV.pdf"

	# Footer settings
	[params.footer]
	# If copyright is not set, author is used
	copyright = "Ellina Kuznetcova"

	# Page license
	[params.license]
	#link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
	#name = "CC-BY-SA-4.0"

	# Credits
	#[[params.credits]]
	# Title is used as URL text
	#title = "HTML5UP"
	# Text will be used to explain the credit
	#text = "Design by"
	#link = "https://html5up.net"